---
title: "Exploring Air Quality in Western U.S. since 1971"
author: Furred Flies (Caleb Weis, Eva Wu, Jimin Han)
output: github_document
---

This file explains the structure of the repository.

## Repo organization 

* [proposal](proposal) folder. This folder includes the RMarkDown and knitted MarkDown documents which contain the information in this proposal.

* [data](data) folder. This folder contains RMarkDown documents used to load, examine, and wrangle data from the RAQSAPI and to load data from other sources, the csv files of data loaded from other sources, as well as the README file consisting of the codebook.

* [Presentation](Presentation) folder. This folder contains code we used to create our slides.

* [write-up](write-up) folder. This folder contains our write-up.

* [shiny](shiny) folder. This folder contains an [app.R](shiny/app.R) document consisting of the code used to build the app and a [data](shiny/data) folder consisting of the data we used to make visualizations in the app. 

* [This](https://hanjimin06.shinyapps.io/furredflies/) is the link to our shiny app website.

* Each folder has a README.Rmd and README.md file that describe the content of the folder.
