---
title: "Data Description"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is the README document explaining the data that we will use for this project. The [data-cleaning-prep.Rmd](data-cleaning-prep.Rmd) file outlines the code we used to obtain and clean the data.

Our data is from the US EPA Air Quality System API, called RAQSAPI and developed by Clinton Mccrowey, a Physical Scientist with the US EPA. This is a very complex API with concentration data on over 25 different air pollutants, on the county, state, Core Based Statistical Area, air monitoring site, primary quality assurance organization, and monitoring agency levels (the latter three are simply different administrative bodies which collect/oversee air quality data; the third is a geographical unit defined by the US Census Bureau), which includes annual, quarterly, and daily summaries stretching back until the early 1960s.

What this API does is provide a multitude of functions that can be used to generate data frames (tibbles) of the available data, and a few functions which also list the pollutants, states, which include data on the pollutants, Core Based Statistical Areas, air monitoring sites, primary quality assurance organizations, and monitoring agencies available in the dataset.

In order to use this API, one must first register their email at https://aqs.epa.gov/data/api/signup?email=myemail@example.com, but replacing "myemail@example.com" with their email. Then, they must simply follow the instructions at file:///Library/Frameworks/R.framework/Versions/4.1/Resources/library/RAQSAPI/doc/RAQSAPIvignette.html.

We have chosen to use data spanning the past 50 years for all 50 US states and Washington, DC, at the county-level, and to include the necessary variables in our data to calculate Air Quality Indices for each quarter (3-month period) within those 50 years. In order to generate our data, we used the function `aqs_quarterlysummary_by_state()`, defining the "parameter," "bdate" (begin date), "edate" (end date), and "state_FIPS" (state FIPS code) variables. The following is a high-level description of an example tibble generated by our function.

| Variable names | Description |
|:-------|:------|
| state_code | Code for chosen state |
| county_code | Code for county in that state |
| site_number | Number of site collecting air pollution data |
| parameter_code | Code for pollutant |
| poc | This parameter is not relevant and will not be used. |
| latitude | Latitude of the site of measurement. |
| longitude | longitude of the site of measurement. |
| datum | Datum associated with latitude and longitude measures. |
| parameter | Name of pollutant. |
| sample_duration | This parameter is not relevant and will not be used. |
| sample_duration_code | This parameter is not relevant and will not be used. |
| sample_duration_type | This parameter is not relevant and will not be used. |
| pollutant_standard | This parameter is not relevant and will not be used. |
| year | Year of recorded measurement. |
| quarter | Quarter of recorded measurement. |
| units_of_measure | Units of measure of pollutant concentration. |
| event_type | This parameter is not relevant and will not be used. |
| observation_count | This parameter is not relevant and will not be used. |
| observation_percent | This parameter is not relevant and will not be used. |
| arithmetic_mean | Arithmetic mean of polllutant concentration. |
| minimum_value | Minimum recorded value of pollutant concentration. |
| maximum_value | Maximum recorded value of pollutant concentration. |
| quarterly_criteria_met | This parameter is not relevant and will not be used. |
| actual_days_gt_std | This parameter is not relevant and will not be used. |
| estimated_days_gt_std | This parameter is not relevant and will not be used. |
| valid_samples | This parameter is not relevant and will not be used. |
| valid_day_count | This parameter is not relevant and will not be used. |
| scheduled_samples | This parameter is not relevant and will not be used. |
| percent_days | This parameter is not relevant and will not be used. |
| percent_one_value | This parameter is not relevant and will not be used. |
| monitoring_agency_code | Monitoring Agency code. |
| monitoring_agency | Monitoring Agency Name. |
| local_site_name | Site name. |
| address | Address of collecting site. |
| state | State name. |
| county | County name. |
| city | City name. |
| tribal_code | This parameter is not relevant and will not be used. |
| tribal_land | This parameter is not relevant and will not be used. |
| cbsa_code | Community Based Statistical Area code. |
| cbsa | Community Based Statistical Area name. |
| date_of_last_change | Date of last collection of pollutant concentration. |

